/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    private Test list = new Test();
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        docField = new javax.swing.JTextField();
        diaCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnGet = new javax.swing.JButton();
        btnClienteMesa = new javax.swing.JButton();
        btnClienteTotal = new javax.swing.JButton();
        btnMesaMaxDia = new javax.swing.JButton();
        btnMesaMinDia = new javax.swing.JButton();
        btnClienteDia = new javax.swing.JButton();
        DiaMasCliente = new javax.swing.JButton();
        ClienteFrecuente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCombo.setBackground(new java.awt.Color(255, 255, 255));
        menuCombo.setForeground(new java.awt.Color(102, 102, 102));
        menuCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", " " }));
        menuCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAFETERIA LA ESQUINA");

        nombreField.setBackground(new java.awt.Color(204, 204, 204));

        docField.setBackground(new java.awt.Color(204, 204, 204));

        diaCombo.setBackground(new java.awt.Color(255, 255, 255));
        diaCombo.setForeground(new java.awt.Color(102, 102, 102));
        diaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        diaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaComboActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre del cliente:");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Documento del cliente:");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mesa");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Dia");

        btnCreate.setBackground(new java.awt.Color(83, 130, 106));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Ingresar");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnGet.setBackground(new java.awt.Color(204, 204, 204));
        btnGet.setForeground(new java.awt.Color(102, 102, 102));
        btnGet.setText("Mostrar");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        btnClienteMesa.setBackground(new java.awt.Color(204, 204, 204));
        btnClienteMesa.setForeground(new java.awt.Color(102, 102, 102));
        btnClienteMesa.setText("Clientes por Mesa");
        btnClienteMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteMesaActionPerformed(evt);
            }
        });

        btnClienteTotal.setBackground(new java.awt.Color(204, 204, 204));
        btnClienteTotal.setForeground(new java.awt.Color(102, 102, 102));
        btnClienteTotal.setText("Total Clientes");
        btnClienteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteTotalActionPerformed(evt);
            }
        });

        btnMesaMaxDia.setBackground(new java.awt.Color(204, 204, 204));
        btnMesaMaxDia.setForeground(new java.awt.Color(102, 102, 102));
        btnMesaMaxDia.setText("Mesa mas usada por dia");
        btnMesaMaxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesaMaxDiaActionPerformed(evt);
            }
        });

        btnMesaMinDia.setBackground(new java.awt.Color(204, 204, 204));
        btnMesaMinDia.setForeground(new java.awt.Color(102, 102, 102));
        btnMesaMinDia.setText("Mesa menos usada por dia");
        btnMesaMinDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesaMinDiaActionPerformed(evt);
            }
        });

        btnClienteDia.setBackground(new java.awt.Color(204, 204, 204));
        btnClienteDia.setForeground(new java.awt.Color(102, 102, 102));
        btnClienteDia.setText("Clientes por dia");
        btnClienteDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteDiaActionPerformed(evt);
            }
        });

        DiaMasCliente.setBackground(new java.awt.Color(204, 204, 204));
        DiaMasCliente.setForeground(new java.awt.Color(102, 102, 102));
        DiaMasCliente.setText("Dia Mas Clientes");
        DiaMasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaMasClienteActionPerformed(evt);
            }
        });

        ClienteFrecuente.setBackground(new java.awt.Color(204, 204, 204));
        ClienteFrecuente.setForeground(new java.awt.Color(102, 102, 102));
        ClienteFrecuente.setText("Cliente Frecuente");
        ClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteFrecuenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMesaMinDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClienteMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClienteDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClienteTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMesaMaxDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DiaMasCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClienteFrecuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGet)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnClienteMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnClienteDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteTotal)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMesaMaxDia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMesaMinDia)
                .addGap(18, 18, 18)
                .addComponent(DiaMasCliente)
                .addGap(18, 18, 18)
                .addComponent(ClienteFrecuente)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuComboActionPerformed

    private void diaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaComboActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        System.out.println(nombreField.getText().toString());
        System.out.println(docField.getText().toString());
        System.out.println(menuCombo.getSelectedItem().toString());
        System.out.println(diaCombo.getSelectedItem().toString());
        Cliente nuevo = new Cliente(docField.getText().toString(), menuCombo.getSelectedItem().toString(), diaCombo.getSelectedItem().toString());
        list.insertar(nuevo);

        JOptionPane.showMessageDialog(this, "Cliente registrado con éxito");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        // TODO add your handling code here:
        list.mostrar();
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnClienteMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteMesaActionPerformed
        // TODO add your handling code here:
        list.clientesMesa("Mesa 1");
        list.clientesMesa("Mesa 2");
        list.clientesMesa("Mesa 3");
    }//GEN-LAST:event_btnClienteMesaActionPerformed

    private void btnClienteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteTotalActionPerformed
        // TODO add your handling code here:
        list.contarClientes();
    }//GEN-LAST:event_btnClienteTotalActionPerformed

    private void btnMesaMaxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesaMaxDiaActionPerformed
        list.mesaMaxDia();
    }//GEN-LAST:event_btnMesaMaxDiaActionPerformed

    private void btnMesaMinDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesaMinDiaActionPerformed
        list.mesaMinDia();
    }//GEN-LAST:event_btnMesaMinDiaActionPerformed

    private void btnClienteDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteDiaActionPerformed
        list.clientesDia();
    }//GEN-LAST:event_btnClienteDiaActionPerformed

    private void DiaMasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaMasClienteActionPerformed
        list.diaConMasClientes();
    }//GEN-LAST:event_DiaMasClienteActionPerformed

    private void ClienteFrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteFrecuenteActionPerformed
        list.clientesRecurrentes();
    }//GEN-LAST:event_ClienteFrecuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClienteFrecuente;
    private javax.swing.JButton DiaMasCliente;
    private javax.swing.JButton btnClienteDia;
    private javax.swing.JButton btnClienteMesa;
    private javax.swing.JButton btnClienteTotal;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnMesaMaxDia;
    private javax.swing.JButton btnMesaMinDia;
    private javax.swing.JComboBox<String> diaCombo;
    private javax.swing.JTextField docField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> menuCombo;
    private javax.swing.JTextField nombreField;
    // End of variables declaration//GEN-END:variables
}
